---
- name: install nginx & start services
  hosts: all
  become: true

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started

ansible-playbook -i hosts playbooks/nginx-install.yml --check -> To check dry-run
ansible-playbook -i hosts playbooks/nginx-install.yml -> To execute the playbook
