---
- name: install tomcat server
  hosts: all
  become: true

  tasks:
  - name: install java
    yum:
      name: java
      state: latest

  - name: download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz # take this URL from google (download tomcat, from latest tomcat website)
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.91.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.91/bin/startup.sh

command: ansible-playbook -i hosts playbooks/tomcat-setup.yml --check (to check dry-run)
         ansible-playbook -i hosts playbooks/tomcat-setup.yml
