---
- name: install tomcat server
  hosts: all
  become: true
  vars:
    - tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz
    - tomcat_package: apache-tomcat-9.0.91

  tasks:
  - name: install java
    yum:
      name: java
      state: latest

  - name: download tomcat server packages
    get_url:
      url: "{{ tomcat_url }}"
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/{{ tomcat_package }}.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh

  OR, we can also do:
  - name: install tomcat server
  hosts: all
  become: true
  vars_files:
    - tomcat_vars

and create a separate file called tomcat_vars and add variable values.
tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz
tomcat_package: apache-tomcat-9.0.91

